"""Cross-cutting Android client-script tests.

Covers: bash -n syntax gates for CI, the Termux:Boot script generated by
install_and_start.sh (including its pgrep double-start guard), installer
safety aborts (missing payload / truncated payload / missing config), the
--sync mtime lookback window, and offline-queue quarantine semantics for
PERMANENT_REJECT_STATUSES.

Bash pieces run under a sandboxed HOME with CALORIE_INSTALL_SRC pointing at
a tmp copy of the real payload, plus PATH shims for the Termux-only tools
(termux-wake-lock) and for anything with side effects (ps, nohup, pgrep,
sleep) so nothing real is killed or started on this machine. Python pieces
import android/upload_photo.py directly and mock requests.post.
"""

import ast
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

BASH = shutil.which("bash")
REPO_ROOT = Path(__file__).resolve().parent.parent
ANDROID_DIR = REPO_ROOT / "android"
WATCHER = ANDROID_DIR / "android_watcher.sh"
INSTALLER = ANDROID_DIR / "install_and_start.sh"

sys.path.append(str(ANDROID_DIR))
import upload_photo

requires_bash = pytest.mark.skipif(BASH is None, reason="bash is not available")

# The installer's payload pre-flight is `python3 -c 'import ast...' <file>`;
# delegate -c to the real interpreter so a corrupt payload really aborts.
# Every other invocation (the --ping at the end) is logged and succeeds.
PYTHON3_SHIM = f"""#!/bin/sh
case "$1" in
  -c) exec "{sys.executable}" "$@" ;;
esac
echo "$@" >> "$HOME/python_calls.log"
exit 0
"""

# ps logs that it was consulted (the kill sweep's only observable) and lists
# no processes, so the sweep can never touch anything real on this machine.
PS_SHIM = """#!/bin/sh
echo "PS $@" >> "$HOME/ps_calls.log"
exit 0
"""

# nohup logs what it WOULD have launched instead of launching it, so the
# installer/boot script never actually start a watcher during tests.
NOHUP_SHIM = """#!/bin/sh
echo "NOHUP $@" >> "$HOME/nohup_calls.log"
exit 0
"""

# {code} is substituted per test: 0 simulates "a watcher already runs",
# 1 simulates "no watcher found".
PGREP_SHIM = """#!/bin/sh
echo "PGREP $@" >> "$HOME/pgrep_calls.log"
exit {code}
"""

NOOP_SHIM = "#!/bin/sh\nexit 0\n"


def _write_shim(path, body):
    path.write_text(body)
    path.chmod(0o755)


def _wait_for(predicate, timeout=10.0):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(0.03)
    return False


def _installer_env(tmp_path, with_config=True):
    """Sandboxed HOME + tmp payload copy + side-effect-free PATH shims."""
    home = tmp_path / "home"
    src = tmp_path / "src"
    bin_dir = tmp_path / "bin"
    for directory in (home, src, bin_dir):
        directory.mkdir()
    shutil.copy(ANDROID_DIR / "upload_photo.py", src / "upload_photo.py")
    shutil.copy(WATCHER, src / "android_watcher.sh")
    _write_shim(bin_dir / "python3", PYTHON3_SHIM)
    _write_shim(bin_dir / "ps", PS_SHIM)
    _write_shim(bin_dir / "nohup", NOHUP_SHIM)
    _write_shim(bin_dir / "sleep", NOOP_SHIM)
    _write_shim(bin_dir / "termux-wake-lock", NOOP_SHIM)
    if with_config:
        (home / ".calorie_tracker_upload.json").write_text(
            '{"ANDROID_API_KEY": "k", "SERVER_URLS": ["http://example.test"]}'
        )
    env = dict(os.environ)
    env["HOME"] = str(home)
    env["PATH"] = str(bin_dir) + os.pathsep + env.get("PATH", "")
    env["CALORIE_INSTALL_SRC"] = str(src)
    env.pop("CALORIE_TRACKER_ANDROID_CONFIG", None)
    return env, home, src, bin_dir


def _run_installer(env):
    return subprocess.run(
        [BASH, str(INSTALLER)],
        env=env,
        capture_output=True,
        text=True,
        timeout=60,
    )


# ---------------------------------------------------------------------------
# 1. Syntax gate for CI
# ---------------------------------------------------------------------------

@requires_bash
@pytest.mark.parametrize("script", [WATCHER, INSTALLER], ids=lambda p: p.name)
def test_bash_syntax_gate(script):
    result = subprocess.run(
        [BASH, "-n", str(script)], capture_output=True, text=True, timeout=30
    )
    assert result.returncode == 0, result.stderr


# ---------------------------------------------------------------------------
# 2. The Termux:Boot script the installer generates
# ---------------------------------------------------------------------------

@requires_bash
def test_installer_generates_pgrep_guarded_boot_script(tmp_path):
    """A successful install writes an executable, syntactically valid boot
    script whose pgrep guard starts the watcher only when none is running."""
    env, home, src, bin_dir = _installer_env(tmp_path)

    result = _run_installer(env)

    assert result.returncode == 0, result.stderr
    assert "Installed Termux:Boot auto-start script." in result.stdout
    boot = home / ".termux" / "boot" / "start-calorie-tracker.sh"
    assert boot.is_file()
    assert os.access(boot, os.X_OK)
    syntax = subprocess.run(
        [BASH, "-n", str(boot)], capture_output=True, text=True, timeout=30
    )
    assert syntax.returncode == 0, syntax.stderr

    # The installer itself launched the watcher (via the nohup shim, so
    # nothing really started). The launch is backgrounded with &, so wait
    # for the shim's log. Then clear it for the boot-script runs below.
    nohup_log = home / "nohup_calls.log"
    assert _wait_for(
        lambda: nohup_log.exists() and "android_watcher.sh" in nohup_log.read_text()
    )
    nohup_log.unlink()

    # pgrep exit 0 = a watcher is already running: the boot script must NOT
    # launch a second one, and still exits cleanly.
    _write_shim(bin_dir / "pgrep", PGREP_SHIM.format(code=0))
    blocked = subprocess.run(
        [BASH, str(boot)], env=env, capture_output=True, text=True, timeout=30
    )
    assert blocked.returncode == 0
    time.sleep(0.3)  # a wrongly-backgrounded nohup would have logged by now
    assert not nohup_log.exists()
    # The guard really consulted pgrep with the watcher pattern.
    assert "-f android_watcher.sh" in (home / "pgrep_calls.log").read_text()

    # pgrep exit 1 = no watcher found: the boot script launches one.
    _write_shim(bin_dir / "pgrep", PGREP_SHIM.format(code=1))
    started = subprocess.run(
        [BASH, str(boot)], env=env, capture_output=True, text=True, timeout=30
    )
    assert started.returncode == 0
    assert _wait_for(
        lambda: nohup_log.exists() and "android_watcher.sh" in nohup_log.read_text()
    )
    assert f"bash {home}/android_watcher.sh" in nohup_log.read_text()


# ---------------------------------------------------------------------------
# 3. Installer safety aborts
# ---------------------------------------------------------------------------

@requires_bash
@pytest.mark.parametrize("missing", ["upload_photo.py", "android_watcher.sh"])
def test_missing_payload_aborts_before_kill_sweep(tmp_path, missing):
    """A missing payload file exits 1 BEFORE the kill sweep: ps is never even
    consulted, and the running watcher's state stays untouched."""
    env, home, src, bin_dir = _installer_env(tmp_path)
    (src / missing).unlink()
    pid_file = home / ".calorie_watcher.pid"
    pid_file.write_text("424242")

    result = _run_installer(env)

    assert result.returncode == 1
    assert f"{missing} not found" in result.stderr
    # The kill sweep's `ps` was never invoked, so nothing could be killed.
    assert not (home / "ps_calls.log").exists()
    assert pid_file.read_text() == "424242"
    assert not (home / "upload_photo.py").exists()
    assert not (home / "android_watcher.sh").exists()
    assert not (home / ".termux").exists()
    assert not (home / "nohup_calls.log").exists()


@requires_bash
def test_truncated_upload_photo_aborts_before_kill_sweep(tmp_path):
    """The real payload cut in half (a truncated adb push) must fail the ast
    pre-flight and abort BEFORE the kill sweep, leaving the watcher alone."""
    env, home, src, bin_dir = _installer_env(tmp_path)
    payload = (ANDROID_DIR / "upload_photo.py").read_bytes()
    truncated = payload[: len(payload) // 2]
    # Precondition: half the payload really is corrupt to the installer's
    # check (strict decode + ast.parse). If a refactor ever makes the halved
    # file parse cleanly, this fails loudly so the cut point can be adjusted.
    with pytest.raises((SyntaxError, UnicodeDecodeError)):
        ast.parse(truncated.decode())
    (src / "upload_photo.py").write_bytes(truncated)
    pid_file = home / ".calorie_watcher.pid"
    pid_file.write_text("424242")

    result = _run_installer(env)

    assert result.returncode == 1
    assert "syntax check" in result.stderr
    assert "left untouched" in result.stderr
    assert not (home / "ps_calls.log").exists()  # kill sweep never ran
    assert pid_file.read_text() == "424242"
    assert not (home / "upload_photo.py").exists()
    assert not (home / "android_watcher.sh").exists()
    assert not (home / "nohup_calls.log").exists()


@requires_bash
def test_missing_config_creates_template_and_exits_1(tmp_path):
    env, home, src, bin_dir = _installer_env(tmp_path, with_config=False)

    result = _run_installer(env)

    assert result.returncode == 1
    assert "rerun this installer" in result.stdout
    config = home / ".calorie_tracker_upload.json"
    assert config.is_file()
    assert (config.stat().st_mode & 0o777) == 0o600
    template = json.loads(config.read_text())  # template must be valid JSON
    assert template["ANDROID_API_KEY"] == "replace-with-the-same-random-value-as-server"
    assert template["SERVER_URLS"]
    # Scripts are installed (the copy precedes the config gate) but nothing
    # was pinged or started with a placeholder config, and the boot script
    # (written after the gate) does not exist yet.
    assert (home / "android_watcher.sh").exists()
    assert not (home / "python_calls.log").exists()
    assert not (home / "nohup_calls.log").exists()
    assert not (home / ".termux" / "boot" / "start-calorie-tracker.sh").exists()


# ---------------------------------------------------------------------------
# 4. upload_photo.py --sync: the mtime lookback window
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def _reset_vpn_cache():
    # The VPN status cache is module-level; keep tests independent.
    upload_photo._VPN_CACHE["checked_at"] = 0.0
    upload_photo._VPN_CACHE["status"] = None
    yield
    upload_photo._VPN_CACHE["checked_at"] = 0.0
    upload_photo._VPN_CACHE["status"] = None


@pytest.fixture
def client_env(tmp_path, monkeypatch):
    """Sandboxed uploader module state: tmp camera + queue dirs, dummy
    server/key, and env-override VPN detection (no subprocess spawns)."""
    camera = tmp_path / "camera"
    camera.mkdir()
    monkeypatch.setattr(upload_photo, "CAMERA_DIR", camera)
    monkeypatch.setattr(upload_photo, "QUEUE_DIR", tmp_path / "queue")
    monkeypatch.setattr(upload_photo, "API_KEY", "test-android-key")
    monkeypatch.setattr(upload_photo, "SERVER_URLS", ["http://mock-server.test"])
    monkeypatch.setattr(upload_photo, "SERVER_URL", "http://mock-server.test")
    monkeypatch.setenv("ANDROID_VPN_ACTIVE", "0")
    return camera


def _drive_sync(mock_post, missing=None):
    """Run sync_photos: /ping answers 200, /reconcile captures the offered
    hash list and reports `missing`, /upload records the uploaded filename."""
    offered = {}
    uploads = []

    def fake_post(url, **kwargs):
        resp = MagicMock()
        resp.status_code = 200
        if url.endswith("/reconcile"):
            offered["hashes"] = list(kwargs["json"]["hashes"])
            resp.json.return_value = {"missing_hashes": list(missing or [])}
        elif url.endswith("/upload"):
            uploads.append(kwargs["files"]["photo"][0])
            resp.json.return_value = {"status": "ok"}
        return resp

    mock_post.side_effect = fake_post
    upload_photo.sync_photos()
    return offered.get("hashes"), uploads


@patch("upload_photo.requests.post")
def test_sync_window_hashes_only_in_window_mtimes(mock_post, client_env, monkeypatch):
    """SYNC_LOOKBACK_DAYS=3 covers today plus the two previous calendar days:
    a 2-day-old photo is offered to /reconcile, a 4-day-old one is not."""
    monkeypatch.setattr(upload_photo, "SYNC_LOOKBACK_DAYS", 3)
    camera = client_env
    now = time.time()
    in_window = camera / "in_window.jpg"
    in_window.write_bytes(b"two-days-old-bytes")
    os.utime(in_window, (now - 2 * 86400, now - 2 * 86400))
    out_window = camera / "out_of_window.jpg"
    out_window.write_bytes(b"four-days-old-bytes")
    os.utime(out_window, (now - 4 * 86400, now - 4 * 86400))

    offered, uploads = _drive_sync(mock_post)

    assert offered == [hashlib.md5(b"two-days-old-bytes").hexdigest()]
    assert uploads == []  # server reported nothing missing


@patch("upload_photo.requests.post")
def test_sync_mtime_governs_over_filename_date(mock_post, client_env):
    """A photo NAMED like yesterday (IMG_YYYYMMDD_HHMMSS) whose mtime is 40
    days old is OUTSIDE the sync window: the mtime governs, not the filename.
    (The filename timestamp only dates the meal once a photo is uploaded.)"""
    camera = client_env
    now = time.time()
    yesterday = time.strftime("%Y%m%d", time.localtime(now - 86400))
    misnamed = camera / f"IMG_{yesterday}_120000.jpg"
    misnamed.write_bytes(b"stale-bytes-named-fresh")
    os.utime(misnamed, (now - 40 * 86400, now - 40 * 86400))
    control = camera / "control.jpg"
    control.write_bytes(b"control-bytes")  # mtime now: inside the window

    offered, uploads = _drive_sync(mock_post)

    assert offered == [hashlib.md5(b"control-bytes").hexdigest()]
    assert hashlib.md5(b"stale-bytes-named-fresh").hexdigest() not in offered
    assert uploads == []


@patch("upload_photo.requests.post")
def test_sync_all_photos_stale_never_contacts_server(mock_post, client_env):
    """When every camera photo's mtime is outside the window, sync returns
    before any network call — no ping, no reconcile."""
    camera = client_env
    now = time.time()
    yesterday = time.strftime("%Y%m%d", time.localtime(now - 86400))
    misnamed = camera / f"IMG_{yesterday}_120000.jpg"
    misnamed.write_bytes(b"stale-bytes-named-fresh")
    os.utime(misnamed, (now - 40 * 86400, now - 40 * 86400))

    upload_photo.sync_photos()

    mock_post.assert_not_called()


@patch("upload_photo.requests.post")
def test_sync_reoffers_photo_already_in_watcher_history(mock_post, client_env, tmp_path):
    """CLIENT-BEHAVIOR PIN for the startup-sync vs seeding race.

    android_watcher.sh seeds only photos OLDER than SEED_FRESH_MINUTES into
    uploaded_files.log; a fresher photo is uploaded by the first polls while
    the startup catch-up sync (sleep 30; upload_photo.py --sync) offers EVERY
    in-window photo to /reconcile. --sync never reads the watcher's history
    file, so when the first poll's upload is still in flight (slow cellular;
    30s request timeout) as /reconcile answers, the same photo IS uploaded a
    second time, concurrently — and on failure both processes can queue their
    own copy of it. Accepted design: the server dedups on original_hash and
    answers 200 for duplicates, so duplicate queue copies unlink on drain.
    This pins the client half of that contract: sync reconciliation is fully
    server-driven; no client-side record can suppress a re-offer.
    """
    camera = client_env
    fresh = camera / "fresh_meal.jpg"
    fresh.write_bytes(b"fresh-meal-bytes")
    fresh_hash = hashlib.md5(b"fresh-meal-bytes").hexdigest()
    # The watcher already uploaded this photo and recorded it in its history
    # file — a file upload_photo.py never opens.
    (tmp_path / "uploaded_files.log").write_text(f"{fresh}\n")

    offered, uploads = _drive_sync(mock_post, missing=[fresh_hash])

    assert offered == [fresh_hash]
    assert uploads == ["fresh_meal.jpg"]  # re-uploaded; the server dedups


# ---------------------------------------------------------------------------
# 5. Offline-queue quarantine: PERMANENT_REJECT_STATUSES
# ---------------------------------------------------------------------------

def _response(status, *, json_body, text=""):
    resp = MagicMock()
    resp.status_code = status
    if json_body:
        resp.json.return_value = (
            {"status": "ok"} if status == 200 else {"error": "rejected"}
        )
    else:
        resp.json.side_effect = ValueError("response body is not JSON")
    resp.text = text
    return resp


@pytest.mark.parametrize("status", sorted(upload_photo.PERMANENT_REJECT_STATUSES))
@patch("upload_photo.requests.post")
def test_queue_app_reject_with_json_body_quarantines(mock_post, status, client_env):
    """An app-origin permanent reject (JSON body) moves the photo to
    rejected/ instead of wedging the queue, and the drain continues on to
    the next queued photo in the same pass."""
    queue = upload_photo.QUEUE_DIR
    queue.mkdir()
    poison = queue / "poison.jpg"
    poison.write_bytes(b"rejected-bytes")
    survivor = queue / "survivor.jpg"
    survivor.write_bytes(b"accepted-bytes")
    now = time.time()
    os.utime(poison, (now - 120, now - 120))  # older mtime drains first
    os.utime(survivor, (now - 60, now - 60))

    sent = []

    def fake_post(url, **kwargs):
        sent.append(kwargs["files"]["photo"][0])
        if len(sent) == 1:
            return _response(status, json_body=True, text='{"error": "rejected"}')
        return _response(200, json_body=True)

    mock_post.side_effect = fake_post

    upload_photo.process_queue()

    assert sent == ["poison.jpg", "survivor.jpg"]
    assert not poison.exists()
    assert (queue / "rejected" / "poison.jpg").read_bytes() == b"rejected-bytes"
    assert not survivor.exists()  # uploaded, not quarantined
    assert not (queue / "rejected" / "survivor.jpg").exists()


@patch("upload_photo.requests.post")
def test_queue_proxy_413_html_body_stays_queued_and_retries_later(mock_post, client_env):
    """The same 413 from an intermediary (HTML body — e.g. a default nginx
    1MB client_max_body_size) is transient: nothing is quarantined, the
    drain pauses, and a later drain retries the very same file."""
    queue = upload_photo.QUEUE_DIR
    queue.mkdir()
    first = queue / "first.jpg"
    first.write_bytes(b"first-bytes")
    second = queue / "second.jpg"
    second.write_bytes(b"second-bytes")
    now = time.time()
    os.utime(first, (now - 120, now - 120))
    os.utime(second, (now - 60, now - 60))

    mock_post.return_value = _response(
        413,
        json_body=False,
        text="<html><h1>413 Request Entity Too Large</h1><hr><center>nginx</center></html>",
    )
    upload_photo.process_queue()

    assert first.read_bytes() == b"first-bytes"  # kept, byte-for-byte
    assert second.exists()
    assert not (queue / "rejected").exists()  # nothing quarantined
    assert mock_post.call_count == 1  # drain paused at the first failure

    # Once the path stops rejecting, the SAME files drain normally.
    mock_post.reset_mock()
    mock_post.return_value = _response(200, json_body=True)
    upload_photo.process_queue()

    assert not first.exists()
    assert not second.exists()
    assert not (queue / "rejected").exists()
    assert mock_post.call_count == 2
