#!/usr/bin/env python3
"""Generate the Python and Dart bindings from shared/ sources.

shared/prompts/*.txt and shared/constants.json are the single source of
truth for everything the server (Python) and the mobile app (Dart) must
agree on. This script emits:

  shared_generated.py               (imported by config.py / telegram_bot.py)
  app/lib/core/shared_generated.dart (imported by the app's core/prompts + modules)

Run with --check to verify the generated files are up to date (used by both
test suites as a drift gate): exit 1 means someone edited a generated file
or the shared source without regenerating.

Encoding rules:
  - The text-handler template in shared/ uses <<TOKEN>> placeholders and
    SINGLE braces for literal JSON. The Python binding re-encodes it for
    str.format (braces doubled, tokens -> {placeholders}); the Dart binding
    keeps <<TOKEN>> and substitutes via replaceAll at runtime (no Dart
    string-interpolation escaping hazards).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "shared"
PY_OUT = ROOT / "shared_generated.py"
DART_OUT = ROOT / "app" / "lib" / "core" / "shared_generated.dart"

HEADER = "AUTO-GENERATED by scripts/sync_shared.py from shared/ — DO NOT EDIT. Edit shared/prompts/*.txt or shared/constants.json and regenerate."

TOKENS = ["TODAY", "WEEKDAY", "YESTERDAY", "MEALS_LIST", "USER_MESSAGE"]


def load_sources():
    food = (SHARED / "prompts" / "food_detection_prompt.txt").read_text(encoding="utf-8")
    text = (SHARED / "prompts" / "text_handler_prompt.txt").read_text(encoding="utf-8")
    constants = json.loads((SHARED / "constants.json").read_text(encoding="utf-8"))
    constants.pop("_comment", None)

    # The estimation-priority "skill" file: an editable evidence ladder
    # (nutrition label > printed weight > brand data > visual estimate)
    # spliced into the photo prompt AT GENERATION TIME, so adding a
    # priority never touches either platform's code. '#' lines are the
    # file's own documentation, not prompt text.
    priority_raw = (SHARED / "prompts" / "estimation_priority.txt").read_text(
        encoding="utf-8"
    )
    priority = "\n".join(
        ln for ln in priority_raw.splitlines() if not ln.startswith("#")
    ).strip()
    if not priority:
        raise SystemExit("estimation_priority.txt has no prompt content")
    if "<<ESTIMATION_PRIORITY>>" not in food:
        raise SystemExit(
            "food_detection_prompt.txt lost its <<ESTIMATION_PRIORITY>> "
            "placeholder — the priority ladder would silently vanish"
        )
    food = food.replace("<<ESTIMATION_PRIORITY>>", priority)
    if "<<ESTIMATION_PRIORITY>>" in food or "Priority 1" not in food:
        raise SystemExit("estimation-priority splice failed")
    return food, text, constants


def python_binding(food, text, constants):
    fmt = text.replace("{", "{{").replace("}", "}}")
    for token in TOKENS:
        fmt = fmt.replace("<<%s>>" % token, "{%s}" % token.lower())
    lines = ['"""%s"""' % HEADER, ""]
    lines.append("FOOD_DETECTION_PROMPT_RAW = %r" % food)
    lines.append("")
    lines.append("TEXT_HANDLER_PROMPT_TEMPLATE = %r" % fmt)
    lines.append("")
    for key, value in constants.items():
        lines.append("%s = %r" % (key.upper(), value))
    lines.append("")
    lines.append("CONSTANTS = %r" % (constants,))
    lines.append("")
    return "\n".join(lines)


def dart_binding(food, text, constants):
    def dart_str(s):
        return "'''\n%s'''" % s.replace("\\", "\\\\").replace("$", "\\$").replace("'''", "\\'\\'\\'")

    def dart_val(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, float):
            return repr(v)
        if isinstance(v, int):
            return str(v)
        return "'%s'" % str(v).replace("\\", "\\\\").replace("'", "\\'")

    def camel(k):
        parts = k.split("_")
        return parts[0] + "".join(p.capitalize() for p in parts[1:])

    lines = ["// %s" % HEADER, "", "library;", ""]
    lines.append("const String sharedFoodDetectionPrompt = %s;" % dart_str(food))
    lines.append("")
    lines.append("const String sharedTextHandlerTemplate = %s;" % dart_str(text))
    lines.append("")
    lines.append("/// Substitutes the `<<TOKEN>>` placeholders. Kept as replaceAll so the")
    lines.append("/// template needs no Dart interpolation escaping.")
    lines.append("String sharedTextHandlerPrompt({")
    lines.append("  required String mealsList,")
    lines.append("  required String userMessage,")
    lines.append("  required String today,")
    lines.append("  required String weekday,")
    lines.append("  required String yesterday,")
    lines.append("}) => sharedTextHandlerTemplate")
    lines.append("    .replaceAll('<<TODAY>>', today)")
    lines.append("    .replaceAll('<<WEEKDAY>>', weekday)")
    lines.append("    .replaceAll('<<YESTERDAY>>', yesterday)")
    lines.append("    .replaceAll('<<MEALS_LIST>>', mealsList)")
    lines.append("    .replaceAll('<<USER_MESSAGE>>', userMessage);")
    lines.append("")
    lines.append("abstract final class SharedConstants {")
    for key, value in constants.items():
        typ = "bool" if isinstance(value, bool) else (
            "double" if isinstance(value, float) else (
                "int" if isinstance(value, int) else "String"))
        lines.append("  static const %s %s = %s;" % (typ, camel(key), dart_val(value)))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    food, text, constants = load_sources()
    outputs = {PY_OUT: python_binding(food, text, constants),
               DART_OUT: dart_binding(food, text, constants)}
    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            if check:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.write_text(content, encoding="utf-8")
                print("wrote %s" % path.relative_to(ROOT))
    if check:
        if stale:
            print("STALE generated bindings (run scripts/sync_shared.py): %s" % ", ".join(stale))
            return 1
        print("shared bindings in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
