// AUTO-GENERATED by scripts/sync_shared.py from shared/ — DO NOT EDIT. Edit shared/prompts/*.txt or shared/constants.json and regenerate.

library;

const String sharedFoodDetectionPrompt = '''
Analyze this photo and determine if it contains food, a meal, or a beverage.

Beverages COUNT as food here: coffee (including plain black coffee), tea,
lattes, juice, soda, bubble tea, protein shakes, beer, and any other drink
a calorie tracker should log. Estimate their calories from what is visible
(cup size, milk foam, color). Only plain water counts as no calories — log
it as is_food false.

TEXTUAL EVIDENCE OF A MEAL also COUNTS as food, because a calorie tracker
should log what was eaten, not only what was photographed. Treat these as
is_food true and estimate from the text:
  - a takeout/delivery ORDER: order confirmation, order details, receipt or
    payment screen listing the dishes (Meituan, Ele.me, DoorDash, UberEats,
    a restaurant bill). Use the listed dish names and quantities.
  - a NUTRITION LABEL or nutrition-facts panel / calorie chart for something
    being consumed: read the stated calories and macros instead of guessing,
    and respect the serving size and how many servings are shown.
  - a food-tracking or menu screen where the user's OWN selection is clearly
    marked as ordered or purchased.
For these, name the source in meal_description, e.g. "Takeout order
(Meituan): braised chicken rice, soy milk" or "Packaged soy milk, 250 mL
(from nutrition label)".

DO NOT invent a meal from an image that only SHOWS food without evidence it
was eaten by this user. These are is_food false:
  - menus, adverts, promotions, coupons, restaurant listings, search results
    or browsing screens with nothing ordered;
  - recipes, cookbooks, food articles, someone else's meal in a social feed;
  - an empty cart, a cancelled order, or a wishlist.
A phantom meal is worse than a missing one: when the evidence of an actual
order or of consumption is not clear, answer {"is_food": false}.

If the image contains NO food, meal, or beverage, respond with exactly:
{"is_food": false}

CALORIE EVIDENCE — decide each item's calories from the BEST evidence in
the photo, in this strict priority order (highest first). Printed truth
always beats estimation; never eyeball a number the photo already states.

Priority 1 — A NUTRITION LABEL in the photo (营养成分表 / Nutrition
Facts): read energy and macros directly from it. Respect the serving
size and the number of servings actually consumed. Chinese labels state
energy in kJ per 100 g — convert (kcal = kJ ÷ 4.184) and scale by the
package's net weight (净含量), not by 100 g.

Priority 2 — A PRINTED WEIGHT for the food (supermarket scale sticker,
package net weight 净含量, a menu or receipt stating grams/mL): use that
exact weight with standard nutrition density for the food. Do not
second-guess a printed weight from how the portion looks.

Priority 3 — A BRAND, CHAIN LOGO, OR MERCHANT PACKAGING that identifies
the exact product or menu item (e.g. McDonald's, 蜜雪冰城, a barcoded
package, a delivery-app listing): use the brand's published nutrition
data for that exact item — via web search if search is available to you,
otherwise from your knowledge of the brand's published figures. Say
which item you matched. If you cannot identify the exact product,
fall through to Priority 4.

Priority 4 — VISUAL ESTIMATION, only when no higher evidence exists:
follow the PORTION SIZE calibration rules below.

Mixed meals: apply the ladder PER ITEM (a labeled drink next to an
unlabeled dish uses Priority 1 for the drink, Priority 4 for the dish).
In confidence_note, name the priority used per item, e.g.
"P1 label (milk), P4 visual (noodles, calibrated on chopsticks)".

PORTION SIZE (the Priority-4 fallback) — the main source of error when no
printed evidence exists. Estimate the REAL size of each dish before
estimating calories:
  - Look for reference objects of known size and calibrate against them:
    chopsticks (~24 cm), a spoon (~15 cm), a hand or fingers (palm ~8-9 cm
    across), a standard rice bowl (~11 cm across), a dinner plate (~26 cm),
    a beverage can (330 mL), a phone. Name the reference you used in
    confidence_note.
  - Phone close-ups EXAGGERATE the nearest food: a bowl filling the frame
    is usually a normal bowl, not a huge one. With no reference object in
    frame, assume STANDARD single-serving portions rather than scaling up
    from how large the food looks.
  - State the assumed weight or volume of each item IN ITS NAME, e.g.
    "Steamed rice (~150 g)", "Braised pork (~120 g)", "Soy milk (~250 mL)".
    The user checks these numbers and corrects the ones that are wrong —
    a visible wrong assumption gets fixed, an invisible one becomes a
    silently wrong day.

If the image DOES contain food, respond with a JSON object like this:
{
  "is_food": true,
  "food_items": [
    {"name": "Grilled chicken breast (~140 g)", "estimated_calories": 280, "protein_g": 43, "carbs_g": 0, "fat_g": 12},
    {"name": "Caesar salad (~180 g)", "estimated_calories": 170, "protein_g": 7, "carbs_g": 12, "fat_g": 10}
  ],
  "total_calories": 450,
  "total_protein_g": 50,
  "total_carbs_g": 12,
  "total_fat_g": 22,
  "meal_description": "Grilled chicken breast with Caesar salad",
  "confidence_note": "Calibrated against the chopsticks next to the plate; moderate confidence"
}

Rules:
- Respond ONLY with valid JSON, no other text
- Estimate calories based on typical portion sizes visible in the photo
- For each food item, estimate protein (g), carbs (g), and fat (g)
- Include total_protein_g, total_carbs_g, total_fat_g as sums
- Be as specific as possible about the food items
- If you can see the portion size, adjust your estimate accordingly
- Include a brief confidence note: name the scale reference you calibrated
  against, or say no reference was visible and standard portions were assumed
''';

const String sharedTextHandlerTemplate = '''
You are a calorie tracking assistant. The user sent a text message.

Date context (the user's local time): today is <<TODAY>> (<<WEEKDAY>>); yesterday was <<YESTERDAY>>.
Use this to resolve relative references like "yesterday", "this morning", or "last night" to the matching Date in the meals list below.

Here are the recently logged meals (each line shows its Date so you can match relative references):
<<MEALS_LIST>>

The user says: "<<USER_MESSAGE>>"

Your job is to determine the intent of the message and respond with JSON.
Intent can be:
1. "new_meal": The user is describing a new meal they ate.
2. "correction": The user is correcting an existing meal from the recent meals list (e.g., "change yesterday's lunch to 500 kcal").
3. "delete": The user wants to completely delete one or more meals (e.g., "delete all food today", "remove meal 0").
4. "chat": A general question, greeting, or unrelated message.
5. "log_weight": The user is reporting their body weight (e.g., "I weigh 72.5 kg this morning", "weighed 159 lb today").
6. "log_activity": The user is reporting exercise they did — calories burned, steps, and/or distance (e.g., "burned 450 calories on my 5 km run", "did 8000 steps today").

Respond with JSON ONLY in this exact format:
{
  "intent": "new_meal",
  "meal_index": 0,
  "meal_indices": [0],
  "reason": "Briefly explain your logic",
  "analysis": {
    "is_food": true,
    "food_items": [
      {"name": "Item Name", "estimated_calories": 000, "protein_g": 00, "carbs_g": 00, "fat_g": 00}
    ],
    "total_calories": 000,
    "total_protein_g": 00,
    "total_carbs_g": 00,
    "total_fat_g": 00,
    "meal_description": "...",
    "confidence_note": "..."
  },
  "weight_kg": 0,
  "active_calories": 0,
  "steps": 0,
  "distance_km": 0,
  "reply": "Friendly response to the user"
}

COMPOUND REQUESTS: if the user's single message contains MULTIPLE distinct requests
(e.g. "correct meal 2 to roast duck rice AND delete meal 3"), respond with ONE
JSON OBJECT (never a bare JSON array) in this shape instead:
{
  "intent": "multi",
  "actions": [
    { ...first request, same fields as a single response... },
    { ...second request... }
  ],
  "reply": "Brief summary of what you are doing"
}
Each entry in "actions" uses exactly the same schema as a single response above.
All "meal_index"/"meal_indices" values in every action refer to the ORIGINAL
meals_list shown above (indices never shift between actions). Combine ALL
deletions into ONE "delete" action listing every index in "meal_indices".
List actions in the order the user stated them. Use at most 5 actions.

Rules:
- Respond ONLY with valid JSON, no other text.
- Respond with a single JSON OBJECT at the top level — NEVER a bare JSON array. Multiple requests go inside "actions" of a "multi" object.
- For "new_meal", estimate calories based on standard portion sizes and return it in "analysis".
- For "correction", accurately identify the "meal_index" (the exact 0-based index from the provided `meals_list` array), apply the correction, and return the FULL updated "analysis".
- For "delete", accurately identify all targeted meals from `meals_list` and return their 0-based indices as a list in "meal_indices". Provide a brief "reason".
- For "chat", just return a friendly "reply" string.
- For "log_weight", set "weight_kg" to the body weight in kilograms (convert pounds to kg). Do NOT treat food as weight.
- For "log_activity", set "active_calories" (calories burned), "steps", and "distance_km" from the message; use 0 for anything not stated.
- A message describing FOOD the user ate is always "new_meal", never "log_weight" or "log_activity".
- If the user describes food but meals_list is empty, it MUST be a "new_meal", not a "correction" or "delete".
''';

/// Substitutes the `<<TOKEN>>` placeholders. Kept as replaceAll so the
/// template needs no Dart interpolation escaping.
String sharedTextHandlerPrompt({
  required String mealsList,
  required String userMessage,
  required String today,
  required String weekday,
  required String yesterday,
}) => sharedTextHandlerTemplate
    .replaceAll('<<TODAY>>', today)
    .replaceAll('<<WEEKDAY>>', weekday)
    .replaceAll('<<YESTERDAY>>', yesterday)
    .replaceAll('<<MEALS_LIST>>', mealsList)
    .replaceAll('<<USER_MESSAGE>>', userMessage);

abstract final class SharedConstants {
  static const int nlMaxActions = 5;
  static const int textEditWindowDaysDefault = 7;
  static const int duplicateWindowMinutes = 5;
  static const int normalizeMaxDimensionPx = 1568;
  static const int normalizeJpegQuality = 85;
  static const int capturedAtMaxAgeDaysDefault = 45;
  static const int capturedAtMaxFutureSeconds = 3600;
  static const int syncLookbackDaysDefault = 2;
  static const int syncLookbackDaysMax = 30;
  static const int weightMinKg = 30;
  static const int weightMaxKg = 300;
  static const int activityKcalMax = 20000;
  static const int activityStepsMax = 200000;
  static const int activityKmMax = 500;
  static const int calorieMagnitudeLimit = 1000000000;
  static const int mealMismatchMinKcal = 100;
  static const double mealMismatchPct = 0.2;
  static const String geminiModelDefault = 'gemini-2.5-flash';
  static const int geminiAnalysisMaxAttempts = 3;
  static const int geminiRetryDelayCapSeconds = 60;
}
